# Site settings
title: Markus Östberg
email: markus@ostberg.dev
description: >
  Software Engineer fascinated by the web, language processing, machine learning and big data.
baseurl: ""
url: "https://www.ostberg.dev"
github_username:  markusos
linkedin_username: markusos
paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
