# Site settings
title: Markus Östberg
email: markusos@kth.se
description: > # this means to ignore newlines until "baseurl:"
  Swedish expat living in Washington, DC. Software Engineer fascinated by the web,
  language processing, machine learning and robotics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://markusos.github.io/"
twitter_username: markus_ostberg
github_username:  markusos

# Build settings
markdown: kramdown
