# Site settings
title: Markus Östberg
email: markus@ostberg.dev
description: >
  Software Engineer fascinated by the web, language processing, machine learning and robotics.
baseurl: ""
url: "http://markusos.github.io/"
twitter_username: markus_ostberg
github_username:  markusos
linkedin_username: markusos
paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
